# Generated by Django 5.2.17 on 2026-08-04 19:07

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessReveal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "fields_revealed",
                    models.JSONField(
                        default=list, help_text='e.g. ["gate_code", "alarm_code"]'
                    ),
                ),
                (
                    "acknowledged",
                    models.BooleanField(
                        default=False,
                        help_text="User confirmed the logging warning before proceeding.",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_flagged", models.BooleanField(db_index=True, default=False)),
                (
                    "flag_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True, default="")),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_reveals",
                        to="customers.servicelocation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_reveals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Access reveal",
                "verbose_name_plural": "Access reveals",
                "ordering": ("-created_at",),
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"],
                        name="audit_acces_organiz_ef59f3_idx",
                    ),
                    models.Index(
                        fields=["organization", "user", "created_at"],
                        name="audit_acces_organiz_390b83_idx",
                    ),
                    models.Index(
                        fields=["organization", "is_flagged", "created_at"],
                        name="audit_acces_organiz_5f1ebf_idx",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
