# Generated by Django 5.2.17 on 2026-09-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_taxable",
            field=models.BooleanField(
                default=False, help_text="Whether sales tax applies to this service."
            ),
        ),
    ]
