# Generated by Django 5.2.17 on 2026-09-22 16:38

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_invoice_created_by_invoice_issued_by"),
        ("organizations", "0005_stripe_connect"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="dispute_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Stripe's word: needs_response, won, lost.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="disputed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="fee_cents",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                ("event_id", models.CharField(max_length=255)),
                ("account", models.CharField(blank=True, default="", max_length=64)),
                ("type", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("ignored", "Ignored"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stripe_events",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe event",
                "verbose_name_plural": "Stripe events",
                "ordering": ("-created_at",),
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["organization", "type"],
                        name="billing_str_organiz_6e6296_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_id", "account"),
                        name="one_stripe_event_per_id_and_account",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
