# Generated by Django 5.2.17 on 2026-08-04 18:38

import base.fields
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="For commercial accounts.",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=30
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "Text message"),
                            ("phone", "Phone call"),
                        ],
                        default="email",
                        max_length=16,
                    ),
                ),
                (
                    "billing_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "billing_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "billing_city",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "billing_state",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "billing_postal_code",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "billing_country",
                    models.CharField(blank=True, default="US", max_length=2),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="lead",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="How they found you.",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Set only if this customer has portal access.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "ordering": ("last_name", "first_name", "company_name"),
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ServiceLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='e.g. "Home", "Rental - Oak St".',
                        max_length=255,
                    ),
                ),
                ("line1", models.CharField(max_length=255)),
                ("line2", models.CharField(blank=True, default="", max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(db_index=True, max_length=30)),
                ("country", models.CharField(default="US", max_length=2)),
                ("square_feet", models.PositiveIntegerField(blank=True, null=True)),
                ("bedrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "bathrooms",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Half baths as .5",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("parking_notes", models.TextField(blank=True, default="")),
                (
                    "access_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Non-sensitive entry instructions.",
                    ),
                ),
                ("gate_code", base.fields.EncryptedTextField(blank=True, default="")),
                ("alarm_code", base.fields.EncryptedTextField(blank=True, default="")),
                (
                    "key_location",
                    base.fields.EncryptedTextField(blank=True, default=""),
                ),
                ("has_pets", models.BooleanField(default=False)),
                ("pet_notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="customers.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service location",
                "verbose_name_plural": "Service locations",
                "ordering": ("customer", "label"),
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["organization", "created_at"],
                name="customers_c_organiz_c9e179_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("first_name__gt", ""),
                    ("last_name__gt", ""),
                    ("company_name__gt", ""),
                    _connector="OR",
                ),
                name="customer_has_a_name",
            ),
        ),
        migrations.AddIndex(
            model_name="servicelocation",
            index=models.Index(
                fields=["organization", "created_at"],
                name="customers_s_organiz_8d0fbd_idx",
            ),
        ),
    ]
