# Generated by Django 5.2.17 on 2026-09-17 21:17

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobphoto",
            name="image",
            field=models.ImageField(
                upload_to="job_photos/%Y/%m/",
                validators=[base.validators.MaxFileSize(10)],
            ),
        ),
    ]
