# Generated by Django 5.2.17 on 2026-08-04 18:22

import django.db.models.manager
import organizations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, editable=False, null=True
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "timezone",
                    models.CharField(
                        default="America/Denver",
                        help_text="IANA timezone name, e.g. America/Denver.",
                        max_length=64,
                        validators=[organizations.models.validate_timezone],
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_state",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "address_postal_code",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "address_country",
                    models.CharField(blank=True, default="US", max_length=2),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organization_logos/"
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(blank=True, default="", max_length=7),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ("name",),
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
