# Generated by Django 5.2.17 on 2026-09-14 19:58

import datetime
import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="business_hours_end",
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AddField(
            model_name="organization",
            name="business_hours_start",
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name="organization",
            name="reveal_buffer_after_minutes",
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name="organization",
            name="reveal_buffer_before_minutes",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="organization",
            name="working_days",
            field=models.JSONField(
                blank=True,
                default=organizations.models.default_working_days,
                help_text="ISO weekday numbers: 1 = Monday .. 7 = Sunday.",
                validators=[organizations.models.validate_working_days],
            ),
        ),
    ]
