# Generated by Django 5.2.17 on 2026-09-17 21:17

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_business_hours_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="organization_logos/",
                validators=[base.validators.MaxFileSize(2)],
            ),
        ),
    ]
