# Generated by Django 5.2.17 on 2026-09-17 22:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_upload_size_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="invoice_footer",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Printed at the foot of every invoice, e.g. "Make checks payable to ...".',
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="invoice_prefix",
            field=models.CharField(
                default="INV",
                help_text="Prefix on invoice numbers, e.g. INV-0001.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="invoice_terms_days",
            field=models.PositiveSmallIntegerField(
                default=14, help_text="Days from issue to the due date."
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="no_access_fee_type",
            field=models.CharField(
                choices=[
                    ("none", "No charge"),
                    ("flat", "Flat amount"),
                    ("percent", "Percentage of the visit price"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="no_access_fee_value",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Cents when the fee is flat, a percentage when it is proportional.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.000"))],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tax_rate_percent",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.000"),
                help_text="Sales tax rate as a percentage, e.g. 8.250 for 8.25%.",
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.000"))],
            ),
        ),
    ]
