# Generated by Django 5.2.17 on 2026-09-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organization_invoice_footer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="stripe_account_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_charges_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_connected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_details_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("stripe_account_id", ""), _negated=True),
                    ("deleted_at__isnull", True),
                ),
                fields=("stripe_account_id",),
                name="one_organization_per_stripe_account",
            ),
        ),
    ]
